// import { Button, VerticalBox } from "std-widgets.slint";

// export component AppWindow inherits Window {
//     in-out property<int> counter: 42;
//     callback request-increase-value();
//     VerticalBox {
//         Text {
//             text: "Counter: \{root.counter}";
//         }
//         // Button {
//         //     text: "Increase value";
//         //     clicked => {
//         //         root.request-increase-value();
//         //     }
//         // }
//     }
// }

import {VerticalBox, HorizontalBox, Button, TextEdit, StyleMetrics} from "std-widgets.slint";
import { SideBar } from "side_bar.slint";
// import source_code_pro font from system
// import "/usr/share/fonts/TTF/JetBrainsMonoNLNerdFont-Thin.ttf";

// style GlobalStyle {
//     font-family: "Arial", sans-serif;
//     font-size: 14px;
// }

// MainWindow := Window {
export component AppWindow inherits Window{
    width: 800px;
    height: 600px;
    // default-font-family: "Source Code Pro Mono";
    default-font-family: "JetBrains Mono NL Nerd Font";
    
    HorizontalBox {
        // Sidebar with buttons
        // VerticalBox {
        //     Button { text: "Button 1"; }
        //     Button { text: "Button 2"; }
        //     Button { text: "Button 3"; }
        //     // Add more buttons as needed
        //     width: 20%;
        // }
        side-bar := SideBar {
            title: @tr("Slint Widgets Gallery");
            model: [@tr("Menu" => "Controls"), @tr("Menu" => "ListView"), @tr("Menu" => "TableView"), @tr("Menu" => "TextEdit"), @tr("Menu" => "Easings"), @tr("Menu" => "About")];
        }

        VerticalBox {
            Text {
                text: "Main Content Area";
                font-family: "JetBrains Mono NL Nerd Font";
            }
            TextEdit {
                font-size: 14px;
            }
            TextEdit {

            }
            HorizontalBox {
                padding-left: 300px;
                Button {
                    text: "Stop";
                }
                Button {
                    text: "Send";
                }
            }
        }
    }
}
